/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AUTO-GENERATED by scripts/update-rates.mjs from the Central Bank of Kenya
 * "Trade Weighted Average Indicative Rates" CSV. Do not edit by hand —
 * run `npm run update-rates` after downloading a fresh CSV.
 */

export interface FxRate {
  label: string;
  value: string;
}

export const exchangeRates = {
  asOf: "4 Jun 2026",
  source: "Central Bank of Kenya (indicative)",
  rates: [
    {
      "label": "USD/KES",
      "value": "129.37"
    },
    {
      "label": "GBP/KES",
      "value": "173.71"
    },
    {
      "label": "EUR/KES",
      "value": "150.11"
    },
    {
      "label": "AED/KES",
      "value": "35.22"
    },
    {
      "label": "CNY/KES",
      "value": "19.11"
    },
    {
      "label": "ZAR/KES",
      "value": "7.92"
    }
  ] as FxRate[],
};
