// Update the site's exchange rates from a Central Bank of Kenya CSV.
//
// 1. Download "TRADE WEIGHTED AVERAGE INDICATIVE RATES.csv" from
//    https://www.centralbank.go.ke/forex/  (saves to your Downloads).
// 2. Run:  npm run update-rates
//    (or point at a specific file:  npm run update-rates -- "C:\\path\\to\\file.csv")
// 3. Commit + push:  git commit -am "Update FX rates" && git push
//
// It reads the most recent date in the CSV and writes src/data/exchangeRates.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

// Which currencies to show, in order. CBK label -> display pair.
// Edit this list to change what appears in the ticker.
const DISPLAY = [
  ["US DOLLAR", "USD/KES"],
  ["STG POUND", "GBP/KES"],
  ["EURO", "EUR/KES"],
  ["AE DIRHAM", "AED/KES"],
  ["CHINESE YUAN", "CNY/KES"],
  ["SA RAND", "ZAR/KES"],
];

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const csvPath =
  process.argv[2] || join(homedir(), "Downloads", "TRADE WEIGHTED AVERAGE INDICATIVE RATES.csv");

const raw = readFileSync(csvPath, "utf8").trim();
const rows = raw
  .split(/\r?\n/)
  .slice(1) // drop header
  .map((line) => line.replace(/^"|"$/g, "").split('","'))
  .filter((cols) => cols.length === 3);

// Parse "DD/MM/YYYY" -> Date.
const toDate = ([d]) => {
  const [dd, mm, yyyy] = d.split("/").map(Number);
  return new Date(yyyy, mm - 1, dd);
};

// Find the most recent date in the file.
const latest = rows.reduce((max, r) => {
  const d = toDate(r);
  return d > max ? d : max;
}, new Date(0));
const latestKey = `${String(latest.getDate()).padStart(2, "0")}/${String(latest.getMonth() + 1).padStart(2, "0")}/${latest.getFullYear()}`;

const forLatest = new Map(
  rows.filter(([d]) => d === latestKey).map(([, currency, rate]) => [currency.trim(), rate]),
);

const rates = DISPLAY.flatMap(([cbkLabel, pair]) => {
  const v = forLatest.get(cbkLabel);
  if (v == null) {
    console.warn(`⚠️  "${cbkLabel}" not found for ${latestKey} — skipping`);
    return [];
  }
  return [{ label: pair, value: Number(v).toFixed(2) }];
});

const asOf = `${latest.getDate()} ${MONTHS[latest.getMonth()]} ${latest.getFullYear()}`;

const out = `/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AUTO-GENERATED by scripts/update-rates.mjs from the Central Bank of Kenya
 * "Trade Weighted Average Indicative Rates" CSV. Do not edit by hand —
 * run \`npm run update-rates\` after downloading a fresh CSV.
 */

export interface FxRate {
  label: string;
  value: string;
}

export const exchangeRates = {
  asOf: ${JSON.stringify(asOf)},
  source: "Central Bank of Kenya (indicative)",
  rates: ${JSON.stringify(rates, null, 2).replace(/\n/g, "\n  ")} as FxRate[],
};
`;

writeFileSync(join("src", "data", "exchangeRates.ts"), out);
console.log(`Updated src/data/exchangeRates.ts — ${rates.length} rates as of ${asOf}:`);
for (const r of rates) console.log(`  ${r.label.padEnd(9)} ${r.value}`);
