// Update the site's exchange rates from a Central Bank of Kenya CSV.
//
// 1. Download "TRADE WEIGHTED AVERAGE INDICATIVE RATES.csv" from
//    https://www.centralbank.go.ke/forex/  (saves to your Downloads).
// 2. Run:  npm run update-rates
//    (or point at a specific file:  npm run update-rates -- "C:\\path\\to\\file.csv")
// 3. Commit + push:  git commit -am "Update FX rates" && git push
//
// It reads the most recent date in the CSV and writes src/data/exchangeRates.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";
import { homedir } from "node:os";

// Which rates to show, in order. CBK label (exactly as in the CSV) -> display pair.
// Edit this list to change what appears in the ticker.
const DISPLAY = [
  ["US DOLLAR", "USD/KES"],
  ["STG POUND", "GBP/KES"],
  ["EURO", "EUR/KES"],
  ["AE DIRHAM", "AED/KES"],
  ["CHINESE YUAN", "CNY/KES"],
  ["SA RAND", "ZAR/KES"],
  // EAC cross-rates: units of the regional currency per 1 KES
  ["KES / TSHS", "KES/TZS"],
  ["KES / RWF", "KES/RWF"],
  ["KES / BIF", "KES/BIF"],
];

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const args = process.argv.slice(2);
const publish = args.includes("--publish");
const csvPath =
  args.find((a) => !a.startsWith("--")) ||
  join(homedir(), "Downloads", "TRADE WEIGHTED AVERAGE INDICATIVE RATES.csv");

const raw = readFileSync(csvPath, "utf8").trim();
const rows = raw
  .split(/\r?\n/)
  .slice(1) // drop header
  .map((line) => line.replace(/^"|"$/g, "").split('","'))
  .filter((cols) => cols.length === 3);

// Parse "DD/MM/YYYY" -> Date.
const toDate = ([d]) => {
  const [dd, mm, yyyy] = d.split("/").map(Number);
  return new Date(yyyy, mm - 1, dd);
};

// Find the most recent date in the file.
const latest = rows.reduce((max, r) => {
  const d = toDate(r);
  return d > max ? d : max;
}, new Date(0));
const latestKey = `${String(latest.getDate()).padStart(2, "0")}/${String(latest.getMonth() + 1).padStart(2, "0")}/${latest.getFullYear()}`;

const forLatest = new Map(
  rows.filter(([d]) => d === latestKey).map(([, currency, rate]) => [currency.trim(), rate]),
);

const rates = DISPLAY.flatMap(([cbkLabel, pair]) => {
  const v = forLatest.get(cbkLabel);
  if (v == null) {
    console.warn(`⚠️  "${cbkLabel}" not found for ${latestKey} — skipping`);
    return [];
  }
  return [{ label: pair, value: Number(v).toFixed(2) }];
});

const asOf = `${latest.getDate()} ${MONTHS[latest.getMonth()]} ${latest.getFullYear()}`;

const out = `/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AUTO-GENERATED by scripts/update-rates.mjs from the Central Bank of Kenya
 * "Trade Weighted Average Indicative Rates" CSV. Do not edit by hand —
 * run \`npm run update-rates\` after downloading a fresh CSV.
 */

export interface FxRate {
  label: string;
  value: string;
}

export const exchangeRates = {
  asOf: ${JSON.stringify(asOf)},
  source: "Central Bank of Kenya (indicative)",
  rates: ${JSON.stringify(rates, null, 2).replace(/\n/g, "\n  ")} as FxRate[],
};
`;

writeFileSync(join("src", "data", "exchangeRates.ts"), out);
console.log(`Updated src/data/exchangeRates.ts — ${rates.length} rates as of ${asOf}:`);
for (const r of rates) console.log(`  ${r.label.padEnd(9)} ${r.value}`);

// `npm run rates:publish` passes --publish: commit just the rates file and push.
if (publish) {
  try {
    execSync("git add src/data/exchangeRates.ts", { stdio: "inherit" });
    execSync(`git commit -m "Update FX rates (${asOf})"`, { stdio: "inherit" });
    execSync("git push", { stdio: "inherit" });
    console.log("\nPublished — Cloudflare will redeploy shortly.");
  } catch {
    console.log("\nNothing to publish (rates unchanged?) or a git step failed — see above.");
  }
}
